### ISSUE TITLE
Creating the Canonical Spec: Preferred Format

### ISSUE THREAD

**Issue by mitsuhiko** [source-map/source-map-rfc#23]
I would like to take the initiative and actually put the existing v3 spec in an accepted format into this repository. Are there any preferences on which format that should be?

**Comment by jaro-sevcik** [comment]
I am new to standards, but in Chrome, it is generally recommended to use [Bikeshed](https://github.com/speced/bikeshed) and to stick to the [WHATWG guidelines ](https://infra.spec.whatwg.org/).

**Comment by mitsuhiko** [comment]
That works for me. I will then make a PR here with the latest version of the Google Doc translated to `.bs`. I would need someone however to set up github actions as I do not have permissions to do so.

**Comment by mitsuhiko** [comment]
I ported the specification to bikeshed in #24. I will close this issue unless someone really does not like that format.
