### ISSUE TITLE
JSON over HTTP Transport

### ISSUE THREAD

**Issue by mitsuhiko** [source-map/source-map-rfc#34]
The current spec has this in it:

> [XSSI](https://www.google.com/url?q=http%3A%2F%2Fgoogleonlinesecurity.blogspot.com%2F2011%2F05%2Fwebsite-security-for-webmasters.html&sa=D&sntz=1&usg=AFQjCNGfEVwZAC-5zTvoGFDCjdNE25PBcw) attacks could potentially make source maps available to attackers by doing a direct script src to a source map after overriding the Array constructor. This can be effectively prevented by preprending a JavaScript syntax error to the start of the response.
>
> Thus when delivering source maps over HTTP, servers may prepend a line starting with the string “)]}'” to the sourcemap. If the response starts with this string clients must ignore the first line.

Does this still carry relevancy in the current day and age and is this consistently being implemented? I haven't seen source maps actually being prefixed with that character sequence.

**Comment by littledan** [comment]
Rob, Justin and Jar report that this is common enough that we can't remove it.

**Comment by mitsuhiko** [comment]
This is resolved now. A note has been added to the spec as discussed.
