### ISSUE TITLE
GitHub-based development process

### ISSUE THREAD

**Issue by littledan** [source-map/source-map-rfc#9]
It looks like the current source-maps specification is in a Google Doc. This makes it a bit difficult to follow normal GitHub-based development processes, such as making PRs to change the specification. Has this group considered moving the specification checked into a repository to enable this workflow? For example, [Bikeshed](https://github.com/tabatkins/bikeshed) could be used for the specification document itself.

**Comment by concavelenz** [comment]
I don't object to moving it to GitHub, but I don't really see the advantage
of using Bikeshed over just making it a Markdown document.

Regarding, PRs, what change did you have in mind?

**Comment by littledan** [comment]
Specifically for https://github.com/source-map/source-map-rfc/issues/8 . It seems like the source-maps spec is the right place for this, rather than the WebAssembly spec (by analogy to JS and CSS which also don't explain source map integration).

**Comment by littledan** [comment]
About why Bikeshed over Markdown: Bikeshed does use Markdown, but it also has some nice tools for cross-referencing other specs, and a pretty template that makes everything Look Like A Real Spec (TM).

**Comment by mitsuhiko** [comment]
I went ahead and drafted up a version in bikeshed: #24 

That said I have neither permissions here, not do I know who calls the shots here. Can someone help me figure this out?

**Comment by littledan** [comment]
The spec is now landed at https://source-map.github.io/source-map-spec/ so I think we can close this as fixed :)
